image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [529.47872,   0.     , 341.9158 ,
           0.     , 531.43333, 248.25167,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.098495, -0.143511, 0.000605, -0.007701, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [538.29688,   0.     , 337.12233,   0.     ,
           0.     , 542.64069, 248.07323,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
